const Stats = () => {
  return (
    <div className="bg-white py-12 px-6 lg:px-16">
      <h2 className="text-base font-medium text-gray-700 mb-8 uppercase tracking-wide text-center">
        Relevant Stats
      </h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-8 text-center">
        {/* Stat 1 */}
        <div className="border-b md:border-b-0 md:border-r last:border-r-0 md:pr-4 pb-6 md:pb-0">
          <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900">41k+</h3>
          <p className="text-sm sm:text-base text-gray-600 mt-2">Followers on Instagram</p>
        </div>
        {/* Stat 2 */}
        <div className="border-b md:border-b-0 md:border-r last:border-r-0 md:pr-4 pb-6 md:pb-0">
          <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900">400,000+</h3>
          <p className="text-sm sm:text-base text-gray-600 mt-2">Average post reach</p>
        </div>
        {/* Stat 3 */}
        <div className="border-b md:border-b-0 md:border-r last:border-r-0 md:pr-4 pb-6 md:pb-0">
          <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900">24-36</h3>
          <p className="text-sm sm:text-base text-gray-600 mt-2">Primary Audience Age</p>
        </div>
        {/* Stat 4 */}
        <div className="border-b md:border-b-0 md:border-r last:border-r-0 md:pr-4 pb-6 md:pb-0">
          <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900">46k+</h3>
          <p className="text-sm sm:text-base text-gray-600 mt-2">Followers on TikTok</p>
        </div>
        {/* Stat 5 */}
        <div className="border-b md:border-b-0 md:border-r last:border-r-0 md:pr-4 pb-6 md:pb-0">
          <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900">670,000</h3>
          <p className="text-sm sm:text-base text-gray-600 mt-2">Weekly Reach</p>
        </div>
        {/* Stat 6 */}
        <div>
          <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-900">$24,000</h3>
          <p className="text-sm sm:text-base text-gray-600 mt-2">
            Sales generated by one campaign
          </p>
        </div>
      </div>
    </div>
  );
};

export default Stats;
